kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-config-toml
  namespace: gitlab
data:
  config.toml: |
    [[runners]]
      [runners.kubernetes]
        [runners.kubernetes.volumes]
          [[runners.kubernetes.volumes.empty_dir]]
            name = "docker-home"
            mount_path = "/.docker"
            medium = "Memory"
          [[runners.kubernetes.volumes.empty_dir]]
            name = "basher-home"
            mount_path = "/.basher"
            medium = "Memory"

